# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a5b31c82cfff06102b4a6ca685297b6506c445845cfcb1d7a2fccf70e6fbc7335df1254c5f04e82ae461d2cfdfff7416873c7e54a993593db8d1da947d93961d

test:
  secret_key_base: 75afd56d406e24b03de4adcafee85193c01f077796c8c1eeb98deff9fdc8cc67dfa38e72ff9a80f8d6a8584558a1bb23a97cc47871dfca83d4462d48178c4548

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
